server:
  port: 10013
  contextPath: /cardmember
  session:
    timeout: 1800
logging:
  config: classpath:log4j2-dev-spring.yml

#spring配置
spring:
  application:
    name: cardmember
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@32.32.32.32:1521/32
      username: 323232
      password: '3232#pP'
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
        maximumPoolSize: 20 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
        minimumIdle:  5 #连接池中允许的最小空闲连接数
  cache:
    type: guava
    cache-names: merchantDetail,selConfig
    guava:
      spec: maximumSize=500,expireAfterWrite=5m

  #模版引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

#mybatis
mybatis:
  mapperLocations: classpath*:com/zhx/*/*/mapper/*Mapper.xml
  typeAliasesPackage: com.zhx.web



eureka:
  client:
    # 开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:123456@132.32.32.124:8081/eureka/,http://admin:123456@32.32.32.125:9600/eureka/
      # 多个eureka节点
  instance:
    #启用Ip注册
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${random.value}
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 180
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 200

management:
  #关闭安全检测
  security:
    enabled: false
  port: ${server.port}

#监控监控信息设置为非敏感
endpoints:
  health:
    sensitive: false

security:
  basic:
    enabled: false

#配置属性
site:
  #测试
  errorNumber: 1

