spring:
  application:
    name: zuul_server
server:
  port: 8080

zuul:
  routes:
    #服务端负载均衡配置

    coreapiread:
      path: /coreapiread/**
      stripPrefix: false
      #服务的 application.name  不能带下划线
      serviceId: coreapiread
    coreapiwrite:
      path: /coreapiwrite/**
      stripPrefix: false
      serviceId: coreapiwrite
    cardmember:
      path: /cardmember/**
      stripPrefix: false
      serviceId: cardmember


  sensitive-headers:
  add-host-header: true
  add-proxy-headers: true

#超时设置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

eureka:
  client:
    # 开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:123456@132.32.32.124:8081/eureka/,http://admin:123456@132.32.32.125:9600/eureka/
    #设置拉取服务注册信息时间，默认60s   如果要迅速获取服务注册状态，可以缩小该值
    registry-fetch-interval-seconds: 10

  instance:
    #启用Ip注册
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${random.value}
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 90

management:
  #关闭安全检测
  security:
    enabled: false
  port: ${server.port}

security:
  basic:
    enabled: true
  user:
    name: 32
    password: fd32

#监控监控信息设置为非敏感
endpoints:
  health:
    sensitive: false








